CcmTransferHistory:
  type: entity
  table: ccm_transfer_history
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    quantity:
      type: integer
      unsigned: false
      nullable: true
    transferDate:
      type: datetime
      nullable: true
      column: transfer_date
  oneToOne:
    toWarehouse:
      targetEntity: Warehouses
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        to_warehouse_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    ccm:
      targetEntity: ColdChain
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        ccm_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    ccmStatusList:
      targetEntity: CcmStatusList
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        ccm_status_list_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    fromWarehouse:
      targetEntity: Warehouses
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        from_warehouse_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    transferBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        transfer_by:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
