GeoMaps:
  type: entity
  table: geo_maps
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    classification:
      type: string
      length: 100
      fixed: false
      nullable: true
    title:
      type: string
      length: 100
      fixed: false
      nullable: true
    noOfClasses:
      type: integer
      unsigned: false
      nullable: true
      column: no_of_classes
  oneToOne:
    resource:
      targetEntity: Resources
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        resource_id:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
