Resources:
  type: entity
  table: resources
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    resourceName:
      type: string
      length: 100
      fixed: false
      nullable: true
      column: resource_name
    description:
      type: text
      nullable: true
    pageTitle:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: page_title
    metaTitle:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: meta_title
    metaDescription:
      type: text
      nullable: true
      column: meta_description
    rank:
      type: integer
      unsigned: false
      nullable: true
    level:
      type: integer
      unsigned: false
      nullable: true
    parentId:
      type: integer
      unsigned: false
      nullable: true
      column: parent_id
    iconClass:
      type: string
      length: 50
      fixed: false
      nullable: true
      column: icon_class
    createdDate:
      type: datetime
      nullable: true
      column: created_date
    modifiedDate:
      type: datetime
      nullable: true
      column: modified_date
  oneToOne:
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    modifiedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        modified_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    resourceType:
      targetEntity: ResourceTypes
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        resource_type_id:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
