RoleResources:
  type: entity
  table: role_resources
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    permission:
      type: string
      length: null
      fixed: false
      nullable: false
    isDefault:
      type: integer
      unsigned: false
      nullable: false
      column: is_default
  oneToOne:
    resource:
      targetEntity: Resources
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        resource_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    role:
      targetEntity: Roles
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        role_id:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
