Warehouses:
  type: entity
  table: warehouses
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    warehouseName:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: warehouse_name
    population:
      type: float
      nullable: true
    ccemId:
      type: string
      length: 50
      fixed: false
      nullable: true
      column: ccem_id
    startingOn:
      type: datetime
      nullable: false
      column: starting_on
    fromEdit:
      type: datetime
      nullable: false
      column: from_edit
    status:
      type: boolean
      nullable: true
    isPlacementEnable:
      type: boolean
      nullable: true
      column: is_placement_enable
  oneToOne:
    warehouseType:
      targetEntity: WarehouseTypes
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        warehouse_type_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    district:
      targetEntity: Locations
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        district_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    province:
      targetEntity: Locations
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        province_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    stakeholder:
      targetEntity: Stakeholders
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        stakeholder_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    location:
      targetEntity: Locations
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        location_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    stakeholderOffice:
      targetEntity: Stakeholders
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        stakeholder_office_id:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
