ItemPackSizes:
  type: entity
  table: item_pack_sizes
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    itemName:
      type: string
      length: 100
      fixed: false
      nullable: true
      column: item_name
    description:
      type: text
      nullable: true
    numberOfDoses:
      type: integer
      unsigned: false
      nullable: true
      column: number_of_doses
    status:
      type: boolean
      nullable: true
    listRank:
      type: integer
      unsigned: false
      nullable: true
      column: list_rank
    multiplier:
      type: integer
      unsigned: false
      nullable: true
    wastageRateAllowed:
      type: float
      nullable: true
      column: wastage_rate_allowed
    color:
      type: string
      length: 100
      fixed: false
      nullable: true
    createdDate:
      type: datetime
      nullable: true
      column: created_date
    modifiedDate:
      type: datetime
      nullable: false
      column: modified_date
  oneToOne:
    stakeholderActivity:
      targetEntity: StakeholderActivities
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        stakeholder_activity_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    itemCategory:
      targetEntity: ItemCategories
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        item_category_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    itemUnit:
      targetEntity: ItemUnits
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        item_unit_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    item:
      targetEntity: Items
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        item_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    modifiedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        modified_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    vvmGroup:
      targetEntity: VvmGroups
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        vvm_group_id:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
