Placements:
  type: entity
  table: placements
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    quantity:
      type: integer
      unsigned: false
      nullable: true
    isPlaced:
      type: integer
      unsigned: false
      nullable: true
      column: is_placed
    createdDate:
      type: datetime
      nullable: true
      column: created_date
    modifiedDate:
      type: datetime
      nullable: false
      column: modified_date
  oneToOne:
    stockDetail:
      targetEntity: StockDetail
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        stock_detail_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    vvmStage:
      targetEntity: VvmStages
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        vvm_stage:
          referencedColumnName: pk_id
      orphanRemoval: false
    stockBatch:
      targetEntity: StockBatch
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        stock_batch_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    placementTransactionType:
      targetEntity: ListDetail
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        placement_transaction_type_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    modifiedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        modified_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    placementLocation:
      targetEntity: PlacementLocations
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        placement_location_id:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
