StockBatchVvmHistory:
  type: entity
  table: stock_batch_vvm_history
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    quantity:
      type: decimal
      nullable: true
    createdDate:
      type: datetime
      nullable: true
      column: created_date
    modifiedDate:
      type: datetime
      nullable: false
      column: modified_date
  oneToOne:
    modifiedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        modified_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    stockBatchVvm:
      targetEntity: StockBatchVvm
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        stock_batch_vvm_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    stockBatch:
      targetEntity: StockBatch
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        stock_batch_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    vvmStage:
      targetEntity: VvmStages
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        vvm_stage:
          referencedColumnName: pk_id
      orphanRemoval: false
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
