WarehousesDataDraft:
  type: entity
  table: warehouses_data_draft
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    openingBalance:
      type: integer
      unsigned: false
      nullable: true
      column: opening_balance
    receivedBalance:
      type: integer
      unsigned: false
      nullable: true
      column: received_balance
    issueBalance:
      type: integer
      unsigned: false
      nullable: true
      column: issue_balance
    closingBalance:
      type: integer
      unsigned: false
      nullable: true
      column: closing_balance
    wastages:
      type: integer
      unsigned: false
      nullable: true
    vialsUsed:
      type: integer
      unsigned: false
      nullable: true
      column: vials_used
    adjustments:
      type: integer
      unsigned: false
      nullable: true
    reportingStartDate:
      type: datetime
      nullable: true
      column: reporting_start_date
    nearestExpiry:
      type: datetime
      nullable: true
      column: nearest_expiry
    modifiedDate:
      type: datetime
      nullable: false
      column: modified_date
    createdDate:
      type: datetime
      nullable: true
      column: created_date
  oneToOne:
    warehouse:
      targetEntity: Warehouses
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        warehouse_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    modifiedBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        modified_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    createdBy:
      targetEntity: Users
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        created_by:
          referencedColumnName: pk_id
      orphanRemoval: false
    itemPackSize:
      targetEntity: ItemPackSizes
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        item_pack_size_id:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
